### ISSUE TITLE
containerized iamlive proxy doesn't generate --output-file on SIGHUP nor on exit

### ISSUE THREAD

**Issue by timblaktu** [iann0036/iamlive#57]
Thank you for creating this amazing project! My iamlive container is now successfully proxying aws cli requests, as proven by its stdout captured in the following docker log entry, output in response to `aws sts get-caller-identity --debug --profile <myprofile>`:

```
my-iamlive-1  | {"Version":"2012-10-17","Statement":[{"Effect":"Allow","Action":["sts:GetCallerIdentity"],"Resource":"*"}]}
```

..but *it is not dumping this text into its --output-file*.

The iamlive container is based on [this one](https://github.com/unfor19/iamlive-docker), and executes iamlive in its entrypoint as:

```
    /app/iamlive \
        --output-file ${IAMLIVE_SHARED_PATH}/iamlive.log \
        --mode proxy \
        --bind-addr 0.0.0.0:10080 \
        --ca-bundle ${IAMLIVE_SHARED_PATH}/ca.pem \
        --ca-key ${IAMLIVE_SHARED_PATH}/ca.key \
        | jq -c .
```

The `${IAMLIVE_SHARED_PATH}` folder (actually is `/home/appuser/.iamlive`) is the container mount point for a named docker volume that is shared with another "client container" that is being monitored for AWS api calls. Below is the relevant excerpt from the docker compose config that orchestrates these two containers. 

```yaml
services:
  main:
    environment:
      - IAMLIVE_SHARED_PATH=${IAMLIVE_SHARED_PATH}
    .
    .
    .
    build:
      args:
        - IAMLIVE_SHARED_PATH=${DEFAULT_CONTAINER_HOME}/${IAMLIVE_SHARED_FOLDER}
    .
    .
    .
    # Ensure iamlive container is run before main
    depends_on:
      - "iamlive"
    volumes:
      - "dot-iamlive:${DEFAULT_CONTAINER_HOME}/${IAMLIVE_SHARED_FOLDER}:rw"
  iamlive:
    environment:
      - IAMLIVE_SHARED_PATH=${IAMLIVE_SHARED_PATH}
    .
    .
    .
    build:
      args:
        - IAMLIVE_SHARED_PATH=${IAMLIVE_SHARED_PATH}
    .
    .
    .
    user: "${HOST_UID}:${HOST_GID}"
    expose:
       - "${IAMLIVE_LISTENER_HTTP_HTTPS_PORT}"
    volumes:
      - "dot-iamlive:${IAMLIVE_SHARED_PATH}:rw"
volumes:
  dot-iamlive:
```
(All I've removed from the above are many superfluous and noisy variable definitions.) 

Mutual access to the shared volume has already been proven working correctly, since:

1. the `IAMLIVE_SHARED_PATH` mount point in the `iamlive` container is where iamlive dumps the required `ca.pem` and `ca.key` files and 
2. the `IAMLIVE_SHARED_PATH` mount point in the `main` (client) container is where the client application instructs the AWS CLI to read the certificate bundle from, using:

```
export AWS_CA_BUNDLE=${IAMLIVE_SHARED_PATH}/ca.pem
```

As mentioned at the top, I've also proven that this scheme of two applications/containers is working in terms of networking and application configuration. The `iamlive` proxy is receiving the `sts get-caller-identity` request and dumping to stdout a policy document correctly containing a `sts:GetCallerIdentity` action.

# The issue
I've yet to see a `iamlive.log` file get dumped. 

## Use case 1: `iamlive` exits

At first, I had the `main` container sleep several seconds after the successful `aws sts get-caller-identity` transaction, and then exit. Because `main` `depends_on` `iamlive`, `main` is stopped first, then `iamlive`. Here, I expected that the `iamlive` application would be sent and would catch `SIGTERM`, and then run [this code](https://github.com/iann0036/iamlive/blob/4b9af3398b8a435b9222e8396ae38510a80e40a3/iamlivecore/csm.go#L100) to write (and flush??) `GetPolicyDocument()`'s return value to the `outputFileFlag`. Since the file path being written is in a mounted folder backed by docker volume on the host, if this file got written, I expected that to persist until the next container run. (There is nothing in this system that deletes files in that shared volume folder.)

## Use case 2: `SIGHUP`

Next, I modified the project to enable the client application running in the `main` container to send UNIX process signals to other containers, specifically so that it could send `SIGHUP` to the `iamlive` container as a way to force it to dump the policy to disk before exiting. For the curious, this required:

1. sharing with `main` the path to the host's docker daemon socket via a host docker volume, and
2. ensuring the user in `main` has the correct permissions to access that socket, and
3. POSTing to this socket at the URL `http://localhost/containers/<target_container_id>/kill?signal=SIGHUP`

When testing this, however, everything worked just fine (the `POST` gets a 204 No Content` response, which is the expected "successful" result for this api call), _except that the `iamlive.log` file did not get dumped_. I confirmed that the I was using the correct [docker daemon api](https://docs.docker.com/engine/api/v1.41/#tag/Container/operation/ContainerKill) and that I was using the correct `target_container_id` by removing the `?signal=SIGHUP` part of the URL which sends `SIGKILL` by default, and when running observing the `iamlive` container exiting immediately after the request `POST`ed from the client application running in the `main` container.

# Summary

So, this feels like a bug, but I could also use some help in troubleshooting this from the `iamlive` side, so please send me any ideas you have on troubleshooting techniques for this app. I've not seen any debugging or verbose mode, nor have I looked at the source code much yet, but I am now stumped and receptive to any help. I realize that this usage mode is unusual -most people seem to be monitoring AWS cli activity from the host system instead of from another container - but this is why I explained myself so thoroughly. Still, let me know if you need any more info to help.

Thanks again for creating this amazing project!
